### ISSUE TITLE
Some addresses showing as "West Bromwich" when they're not

### ISSUE THREAD

**Issue by pezholio** [OpenAddressesUK/forum#18]
See http://alpha.openaddressesuk.org/addresses?postcode=b74+3ud

The post town should be Sutton Coldfield.

Also occurs on some Solihull and Birmingham addresses

**Comment by giacecco** [comment]
The two West Bromwich addresses appear to be honest mistakes made by people registering their companies there and not realising that their location is actually in Sutton Coldfield. 

@murraydata has checked, and, interestingly, the _B74 3_ postcode sector appears to be actually a good split between Sutton Coldfield and West Bromwich. The kind of confidence calculations we are doing at the moment - whose granularity stops at postcode sectors - will not easily spot the error as we will likely observe the same distribution of addresses between the two towns. Spatial confidence will fix that in the future.

In the meantime, we will rely on validation votes to make the address score less.
