### ISSUE TITLE
Dual language addresses

### ISSUE THREAD

**Issue by peterkwells** [OpenAddressesUK/forum#4]
Feature request from @AngharadStone via Twitter. More detail requested.

**Comment by AngharadStone** [comment]
In Wales every address is recorded and available in dual language - both English and Welsh.
It is not clear how to enter this sort of information in the form.

Would entering the address in both English and Welsh in the same submission form work or would the OpenAddresses system only record 1 version.

Also will the OpenAddresses system know that 2 different address entries refer to 1 address but in 2 different languages?

**Comment by giacecco** [comment]
Hi @AngharadStone . If you've had the opportunity to download the dataset or test drive the API you probably have seen already that 'under the bonnet' we're already managing multiple languages and even aliases within the same language for each entity that makes an address. 

E.g. if you see [the JSON version of the address for our London offices](http://alpha.openaddressesuk.org/addresses/V16up8.json) you'll see something like:

```
{ "address":
    {"url":"http://alpha.openaddressesuk.org/addresses/V16up8",
     "sao":"3RD FLOOR",
     "pao":"65",
     "street":{
         "name":{
             "en":["CLIFTON STREET"],
             "cy":[]},
         "url":"http://alpha.openaddressesuk.org/streets/4T3OPv"},
     "locality": (...)
    }
}
```

... where *cy* is for Cymraeg, of course.

So what you suggest is right and is just a matter of website design. The current form cannot manage multiple language nor multiple aliases: it's a feature we have in our wishlist for Beta. 

In the meantime though feel free to submit the English version of the addresses you would like to contribute.
