### ISSUE TITLE
Missing address, added multiple times

### ISSUE THREAD

**Issue by peterkwells** [OpenAddressesUK/forum#44]
Report from twitter that an address has been added multiple times but is not present in the published database:

https://twitter.com/aileen_heal/status/568759119177523200

The address has been passed by email to Open Addresses. It is confirmed that it passes validation via the Sorting Office API but investigations ongoing as to why it's missing.

**Comment by giacecco** [comment]
Definitely a bug, conversation moved to the Sorting Office issues at https://github.com/OpenAddressesUK/sorting_office/issues/22 .
