### ISSUE TITLE
Turbot - missing submission guidelines

### ISSUE THREAD

**Issue by peterkwells** [OpenAddressesUK/forum#49]
The Turbot engine is missing the submission guidelines:

http://turbot.openaddressesuk.org/
1. Long-term roadmap feature for a fix is here: https://github.com/OpenAddressesUK/roadmap/issues/79
2. Short-term fix is similar to what we did for Sorting Office. Reference the submission guidelines in the landing page or similar.

Gianfranco to fix.

**Comment by giacecco** [comment]
Now scheduled for the ongoing sprint [here](https://github.com/theodi/shared/issues/548).

**Comment by peterkwells** [comment]
This is done. Closing.
