### ISSUE TITLE
Service testing... personal data

### ISSUE THREAD

**Issue by peterkwells** [OpenAddressesUK/forum#52]
This address is:

a) a duplicate
b) contains personal data, my name 

https://alpha.openaddressesuk.org/addresses/mmdAlQ

Can we take it out please?

(don't worry I don't actually live there although I do live close)

**Comment by giacecco** [comment]
Made the removal request into a task at https://github.com/OpenAddressesUK/ernest/issues/30 . The feature of "intercepting" people names was already in the roadmap at https://github.com/OpenAddressesUK/roadmap/issues/80 .

**Comment by pezholio** [comment]
Done! :+1:

**Comment by peterkwells** [comment]
Checked. Looks great to me. Thank you :-)

</ends role play>
