### ISSUE TITLE
API response to use X-Total-Count not Total

### ISSUE THREAD

**Issue by kris-sum** [OpenAddressesUK/forum#55]
It'd be great to use a standardised response header for the 'total' count, which i missed when first checking the API response.

> X-Total-Count instead of Total

source:
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination

Would also be nice to know the number of results in the current pagination set without having to count the elements in the json, either via a page size in the link tag or another header.

**Comment by giacecco** [comment]
@pezholio @floppy what do you think?

**Comment by Floppy** [comment]
Sounds sensible!

**Comment by giacecco** [comment]
Promoted to https://github.com/OpenAddressesUK/theodolite/issues/145 .
