### ISSUE TITLE
Is Open Addresses UK working with openaddresses.io? Also did logo inspiration come from @OpenPlans?

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/forum#7]
From Twitter at https://twitter.com/internetrebecca/status/547134344935251968 and moved here from https://github.com/OpenAddressesUK/theodolite/issues/52 .

**Comment by peterkwells** [comment]
Response in same twitter thread. Our logo was not inspired by @OpenPlans. We continue to try and contact openaddresses.io.
